// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// AvatarRequestsService is an interface for [gitlab.Client.Avatar]
type AvatarRequestsService interface {
	// GetAvatar gets the avatar URL for a user with the given email address.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/avatar.html#get-a-single-avatar-url
	GetAvatar(opt *GetAvatarOptions, options ...RequestOptionFunc) (*Avatar, *Response, error)
}
