// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// BulkImportsService is an interface for [gitlab.Client.BulkImports]
type BulkImportsService interface {
	// StartMigration starts a migration.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/bulk_imports.html#start-a-new-group-or-project-migration
	StartMigration(startMigrationOptions *BulkImportStartMigrationOptions, options ...RequestOptionFunc) (*BulkImportStartMigrationResponse, *Response, error)
}
