// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// CIYMLTemplatesService is an interface for [gitlab.Client.CIYMLTemplate]
type CIYMLTemplatesService interface {
	// ListAllTemplates get all GitLab CI YML templates.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/templates/gitlab_ci_ymls.html#list-gitlab-ci-yaml-templates
	ListAllTemplates(opt *ListCIYMLTemplatesOptions, options ...RequestOptionFunc) ([]*CIYMLTemplateListItem, *Response, error)
	// GetTemplate get a single GitLab CI YML template.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/templates/gitlab_ci_ymls.html#single-gitlab-ci-yaml-template
	GetTemplate(key string, options ...RequestOptionFunc) (*CIYMLTemplate, *Response, error)
}
