// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// EpicsService is an interface for [gitlab.Client.Epics]
type EpicsService interface {
	// ListGroupEpics gets a list of group epics. This function accepts pagination
	// parameters page and per_page to return the list of group epics.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/epics.html#list-epics-for-a-group
	ListGroupEpics(gid interface{}, opt *ListGroupEpicsOptions, options ...RequestOptionFunc) ([]*Epic, *Response, error)
	// GetEpic gets a single group epic.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/epics.html#single-epic
	GetEpic(gid interface{}, epic int, options ...RequestOptionFunc) (*Epic, *Response, error)
	// GetEpicLinks gets all child epics of an epic.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/epic_links.html
	GetEpicLinks(gid interface{}, epic int, options ...RequestOptionFunc) ([]*Epic, *Response, error)
	// CreateEpic creates a new group epic.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/epics.html#new-epic
	CreateEpic(gid interface{}, opt *CreateEpicOptions, options ...RequestOptionFunc) (*Epic, *Response, error)
	// UpdateEpic updates an existing group epic. This function is also used
	// to mark an epic as closed.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/epics.html#update-epic
	UpdateEpic(gid interface{}, epic int, opt *UpdateEpicOptions, options ...RequestOptionFunc) (*Epic, *Response, error)
	// DeleteEpic deletes a single group epic.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/epics.html#delete-epic
	DeleteEpic(gid interface{}, epic int, options ...RequestOptionFunc) (*Response, error)
}
