// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// ExternalStatusChecksService is an interface for [gitlab.Client.ExternalStatusChecks]
type ExternalStatusChecksService interface {
	// ListMergeStatusChecks lists the external status checks that apply to it
	// and their status for a single merge request.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/status_checks.html#list-status-checks-for-a-merge-request
	ListMergeStatusChecks(pid interface{}, mr int, opt *ListOptions, options ...RequestOptionFunc) ([]*MergeStatusCheck, *Response, error)
	// SetExternalStatusCheckStatus sets the status of an external status check.
	//
	// Gitlab API docs:
	// https://docs.gitlab.com/ee/api/status_checks.html#set-status-of-an-external-status-check
	SetExternalStatusCheckStatus(pid interface{}, mergeRequest int, opt *SetExternalStatusCheckStatusOptions, options ...RequestOptionFunc) (*Response, error)
	// ListProjectStatusChecks lists the project external status checks.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/status_checks.html#get-project-external-status-checks
	ListProjectStatusChecks(pid interface{}, opt *ListOptions, options ...RequestOptionFunc) ([]*ProjectStatusCheck, *Response, error)
	// CreateExternalStatusCheck creates an external status check.
	//
	// Gitlab API docs:
	// https://docs.gitlab.com/ee/api/status_checks.html#create-external-status-check
	CreateExternalStatusCheck(pid interface{}, opt *CreateExternalStatusCheckOptions, options ...RequestOptionFunc) (*Response, error)
	// DeleteExternalStatusCheck deletes an external status check.
	//
	// Gitlab API docs:
	// https://docs.gitlab.com/ee/api/status_checks.html#delete-external-status-check
	DeleteExternalStatusCheck(pid interface{}, check int, options ...RequestOptionFunc) (*Response, error)
	// UpdateExternalStatusCheck updates an external status check.
	//
	// Gitlab API docs:
	// https://docs.gitlab.com/ee/api/status_checks.html#update-external-status-check
	UpdateExternalStatusCheck(pid interface{}, check int, opt *UpdateExternalStatusCheckOptions, options ...RequestOptionFunc) (*Response, error)
	// UpdateExternalStatusCheck updates an external status check.
	//
	// Gitlab API docs:
	// https://docs.gitlab.com/ee/api/status_checks.html#retry-failed-status-check-for-a-merge-request
	RetryFailedStatusCheckForAMergeRequest(pid interface{}, mergeRequest int, externalStatusCheck int, options ...RequestOptionFunc) (*Response, error)
}
