// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// FreezePeriodsService is an interface for [gitlab.Client.FreezePeriods]
type FreezePeriodsService interface {
	// ListFreezePeriods gets a list of project project freeze periods.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/freeze_periods.html#list-freeze-periods
	ListFreezePeriods(pid interface{}, opt *ListFreezePeriodsOptions, options ...RequestOptionFunc) ([]*FreezePeriod, *Response, error)
	// GetFreezePeriod gets a specific freeze period for a project.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/freeze_periods.html#get-a-freeze-period-by-a-freeze_period_id
	GetFreezePeriod(pid interface{}, freezePeriod int, options ...RequestOptionFunc) (*FreezePeriod, *Response, error)
	// CreateFreezePeriodOptions adds a freeze period to a specified project.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/freeze_periods.html#create-a-freeze-period
	CreateFreezePeriodOptions(pid interface{}, opt *CreateFreezePeriodOptions, options ...RequestOptionFunc) (*FreezePeriod, *Response, error)
	// UpdateFreezePeriodOptions edits a freeze period for a specified project.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/freeze_periods.html#update-a-freeze-period
	UpdateFreezePeriodOptions(pid interface{}, freezePeriod int, opt *UpdateFreezePeriodOptions, options ...RequestOptionFunc) (*FreezePeriod, *Response, error)
	// DeleteFreezePeriod removes a freeze period from a project. This is an
	// idempotent method and can be called multiple times. Either the hook is
	// available or not.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/freeze_periods.html#delete-a-freeze-period
	DeleteFreezePeriod(pid interface{}, freezePeriod int, options ...RequestOptionFunc) (*Response, error)
}
