// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

import (
	"io"
)

// GenericPackagesService is an interface for [gitlab.Client.GenericPackages]
type GenericPackagesService interface {
	// FormatPackageURL returns the GitLab Package Registry URL for the given artifact metadata, without the BaseURL.
	// This does not make a GitLab API request, but rather computes it based on their documentation.
	FormatPackageURL(pid interface{}, packageName, packageVersion, fileName string) (string, error)
	// PublishPackageFile uploads a file to a project's package registry.
	//
	// GitLab docs:
	// https://docs.gitlab.com/ee/user/packages/generic_packages/index.html#publish-a-package-file
	PublishPackageFile(pid interface{}, packageName, packageVersion, fileName string, content io.Reader, opt *PublishPackageFileOptions, options ...RequestOptionFunc) (*GenericPackagesFile, *Response, error)
	// DownloadPackageFile allows you to download the package file.
	//
	// GitLab docs:
	// https://docs.gitlab.com/ee/user/packages/generic_packages/index.html#download-package-file
	DownloadPackageFile(pid interface{}, packageName, packageVersion, fileName string, options ...RequestOptionFunc) ([]byte, *Response, error)
}
