// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// GeoNodesService is an interface for [gitlab.Client.GeoNodes]
type GeoNodesService interface {
	// CreateGeoNode creates a new Geo Node.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/geo_nodes.html#create-a-new-geo-node
	CreateGeoNode(opt *CreateGeoNodesOptions, options ...RequestOptionFunc) (*GeoNode, *Response, error)
	// ListGeoNodes gets a list of geo nodes.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/geo_nodes.html#retrieve-configuration-about-all-geo-nodes
	ListGeoNodes(opt *ListGeoNodesOptions, options ...RequestOptionFunc) ([]*GeoNode, *Response, error)
	// GetGeoNode gets a specific geo node.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/geo_nodes.html#retrieve-configuration-about-a-specific-geo-node
	GetGeoNode(id int, options ...RequestOptionFunc) (*GeoNode, *Response, error)
	// EditGeoNode updates settings of an existing Geo node.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/geo_nodes.html#edit-a-geo-node
	EditGeoNode(id int, opt *UpdateGeoNodesOptions, options ...RequestOptionFunc) (*GeoNode, *Response, error)
	// DeleteGeoNode removes the Geo node.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/geo_nodes.html#delete-a-geo-node
	DeleteGeoNode(id int, options ...RequestOptionFunc) (*Response, error)
	// RepairGeoNode to repair the OAuth authentication of a Geo node.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/geo_nodes.html#repair-a-geo-node
	RepairGeoNode(id int, options ...RequestOptionFunc) (*GeoNode, *Response, error)
	// RetrieveStatusOfAllGeoNodes get the list of status of all Geo Nodes.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/geo_nodes.html#retrieve-status-about-all-geo-nodes
	RetrieveStatusOfAllGeoNodes(options ...RequestOptionFunc) ([]*GeoNodeStatus, *Response, error)
	// RetrieveStatusOfGeoNode get the of status of a specific Geo Nodes.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/geo_nodes.html#retrieve-status-about-a-specific-geo-node
	RetrieveStatusOfGeoNode(id int, options ...RequestOptionFunc) (*GeoNodeStatus, *Response, error)
}
