// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// GroupIterationsService is an interface for [gitlab.Client.GroupIterations]
type GroupIterationsService interface {
	// ListGroupIterations returns a list of group iterations.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/group_iterations.html#list-group-iterations
	ListGroupIterations(gid interface{}, opt *ListGroupIterationsOptions, options ...RequestOptionFunc) ([]*GroupIteration, *Response, error)
}
