// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// GroupReleasesService is an interface for [gitlab.Client.GroupReleases]
type GroupReleasesService interface {
	// ListGroupReleases gets a list of releases for a group.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/api/group_releases.html#list-group-releases
	ListGroupReleases(gid interface{}, opts *ListGroupReleasesOptions, options ...RequestOptionFunc) ([]*Release, *Response, error)
}
