// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// InvitesService is an interface for [gitlab.Client.Invites]
type InvitesService interface {
	// ListPendingGroupInvitations gets a list of invited group members.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/invitations.html#list-all-invitations-pending-for-a-group-or-project
	ListPendingGroupInvitations(gid interface{}, opt *ListPendingInvitationsOptions, options ...RequestOptionFunc) ([]*PendingInvite, *Response, error)
	// ListPendingProjectInvitations gets a list of invited project members.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/invitations.html#list-all-invitations-pending-for-a-group-or-project
	ListPendingProjectInvitations(pid interface{}, opt *ListPendingInvitationsOptions, options ...RequestOptionFunc) ([]*PendingInvite, *Response, error)
	// GroupInvites invites new users by email to join a group.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/invitations.html#add-a-member-to-a-group-or-project
	GroupInvites(gid interface{}, opt *InvitesOptions, options ...RequestOptionFunc) (*InvitesResult, *Response, error)
	// ProjectInvites invites new users by email to join a project.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/invitations.html#add-a-member-to-a-group-or-project
	ProjectInvites(pid interface{}, opt *InvitesOptions, options ...RequestOptionFunc) (*InvitesResult, *Response, error)
}
