// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// MemberRolesService is an interface for [gitlab.Client.MemberRolesService]
type MemberRolesService interface {
	// ListMemberRoles gets a list of member roles for a specified group.
	//
	// Gitlab API docs:
	// https://docs.gitlab.com/ee/api/member_roles.html#list-all-member-roles-of-a-group
	ListMemberRoles(gid interface{}, options ...RequestOptionFunc) ([]*MemberRole, *Response, error)
	// CreateMemberRole creates a new member role for a specified group.
	//
	// Gitlab API docs:
	// https://docs.gitlab.com/ee/api/member_roles.html#add-a-member-role-to-a-group
	CreateMemberRole(gid interface{}, opt *CreateMemberRoleOptions, options ...RequestOptionFunc) (*MemberRole, *Response, error)
	// DeleteMemberRole deletes a member role from a specified group.
	//
	// Gitlab API docs:
	// https://docs.gitlab.com/ee/api/member_roles.html#remove-member-role-of-a-group
	DeleteMemberRole(gid interface{}, memberRole int, options ...RequestOptionFunc) (*Response, error)
}
