// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// PagesDomainsService is an interface for [gitlab.Client.PagesDomains]
type PagesDomainsService interface {
	// ListPagesDomains gets a list of project pages domains.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pages_domains.html#list-pages-domains
	ListPagesDomains(pid interface{}, opt *ListPagesDomainsOptions, options ...RequestOptionFunc) ([]*PagesDomain, *Response, error)
	// ListAllPagesDomains gets a list of all pages domains.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pages_domains.html#list-all-pages-domains
	ListAllPagesDomains(options ...RequestOptionFunc) ([]*PagesDomain, *Response, error)
	// GetPagesDomain get a specific pages domain for a project.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pages_domains.html#single-pages-domain
	GetPagesDomain(pid interface{}, domain string, options ...RequestOptionFunc) (*PagesDomain, *Response, error)
	// CreatePagesDomain creates a new project pages domain.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pages_domains.html#create-new-pages-domain
	CreatePagesDomain(pid interface{}, opt *CreatePagesDomainOptions, options ...RequestOptionFunc) (*PagesDomain, *Response, error)
	// UpdatePagesDomain updates an existing project pages domain.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pages_domains.html#update-pages-domain
	UpdatePagesDomain(pid interface{}, domain string, opt *UpdatePagesDomainOptions, options ...RequestOptionFunc) (*PagesDomain, *Response, error)
	// DeletePagesDomain deletes an existing prject pages domain.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pages_domains.html#delete-pages-domain
	DeletePagesDomain(pid interface{}, domain string, options ...RequestOptionFunc) (*Response, error)
}
