// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// PipelineSchedulesService is an interface for [gitlab.Client.PipelineSchedules]
type PipelineSchedulesService interface {
	// ListPipelineSchedules gets a list of project triggers.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pipeline_schedules.html#get-all-pipeline-schedules
	ListPipelineSchedules(pid interface{}, opt *ListPipelineSchedulesOptions, options ...RequestOptionFunc) ([]*PipelineSchedule, *Response, error)
	// GetPipelineSchedule gets a pipeline schedule.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pipeline_schedules.html#get-a-single-pipeline-schedule
	GetPipelineSchedule(pid interface{}, schedule int, options ...RequestOptionFunc) (*PipelineSchedule, *Response, error)
	// ListPipelinesTriggeredBySchedule gets all pipelines triggered by a pipeline
	// schedule.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pipeline_schedules.html#get-all-pipelines-triggered-by-a-pipeline-schedule
	ListPipelinesTriggeredBySchedule(pid interface{}, schedule int, opt *ListPipelinesTriggeredByScheduleOptions, options ...RequestOptionFunc) ([]*Pipeline, *Response, error)
	// CreatePipelineSchedule creates a pipeline schedule.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pipeline_schedules.html#create-a-new-pipeline-schedule
	CreatePipelineSchedule(pid interface{}, opt *CreatePipelineScheduleOptions, options ...RequestOptionFunc) (*PipelineSchedule, *Response, error)
	// EditPipelineSchedule edits a pipeline schedule.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pipeline_schedules.html#edit-a-pipeline-schedule
	EditPipelineSchedule(pid interface{}, schedule int, opt *EditPipelineScheduleOptions, options ...RequestOptionFunc) (*PipelineSchedule, *Response, error)
	// TakeOwnershipOfPipelineSchedule sets the owner of the specified
	// pipeline schedule to the user issuing the request.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pipeline_schedules.html#take-ownership-of-a-pipeline-schedule
	TakeOwnershipOfPipelineSchedule(pid interface{}, schedule int, options ...RequestOptionFunc) (*PipelineSchedule, *Response, error)
	// DeletePipelineSchedule deletes a pipeline schedule.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pipeline_schedules.html#delete-a-pipeline-schedule
	DeletePipelineSchedule(pid interface{}, schedule int, options ...RequestOptionFunc) (*Response, error)
	// RunPipelineSchedule triggers a new scheduled pipeline to run immediately.
	//
	// Gitlab API docs:
	// https://docs.gitlab.com/ee/api/pipeline_schedules.html#run-a-scheduled-pipeline-immediately
	RunPipelineSchedule(pid interface{}, schedule int, options ...RequestOptionFunc) (*Response, error)
	// CreatePipelineScheduleVariable creates a pipeline schedule variable.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pipeline_schedules.html#create-a-new-pipeline-schedule
	CreatePipelineScheduleVariable(pid interface{}, schedule int, opt *CreatePipelineScheduleVariableOptions, options ...RequestOptionFunc) (*PipelineVariable, *Response, error)
	// EditPipelineScheduleVariable creates a pipeline schedule variable.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pipeline_schedules.html#edit-a-pipeline-schedule-variable
	EditPipelineScheduleVariable(pid interface{}, schedule int, key string, opt *EditPipelineScheduleVariableOptions, options ...RequestOptionFunc) (*PipelineVariable, *Response, error)
	// DeletePipelineScheduleVariable creates a pipeline schedule variable.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/pipeline_schedules.html#delete-a-pipeline-schedule-variable
	DeletePipelineScheduleVariable(pid interface{}, schedule int, key string, options ...RequestOptionFunc) (*PipelineVariable, *Response, error)
}
