// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

import (
	"io"
)

// ProjectImportExportService is an interface for [gitlab.Client.ProjectImportExport]
type ProjectImportExportService interface {
	// ScheduleExport schedules a project export.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/project_import_export.html#schedule-an-export
	ScheduleExport(pid interface{}, opt *ScheduleExportOptions, options ...RequestOptionFunc) (*Response, error)
	// ExportStatus get the status of export.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/project_import_export.html#export-status
	ExportStatus(pid interface{}, options ...RequestOptionFunc) (*ExportStatus, *Response, error)
	// ExportDownload download the finished export.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/project_import_export.html#export-download
	ExportDownload(pid interface{}, options ...RequestOptionFunc) ([]byte, *Response, error)
	// Import a project from an archive file.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/project_import_export.html#import-a-file
	ImportFromFile(archive io.Reader, opt *ImportFileOptions, options ...RequestOptionFunc) (*ImportStatus, *Response, error)
	// ImportStatus get the status of an import.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/project_import_export.html#import-status
	ImportStatus(pid interface{}, options ...RequestOptionFunc) (*ImportStatus, *Response, error)
}
