// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

import (
	"io"
)

// ProjectMarkdownUploadsService is an interface for [gitlab.Client.ProjectMarkdownUploads]
type ProjectMarkdownUploadsService interface {
	// UploadProjectMarkdown uploads a markdown file to a project.
	//
	// GitLab docs:
	// https://docs.gitlab.com/ee/api/project_markdown_uploads.html#upload-a-file
	UploadProjectMarkdown(pid interface{}, content io.Reader, filename string, options ...RequestOptionFunc) (*ProjectMarkdownUploadedFile, *Response, error)
	// ListProjectMarkdownUploads gets all markdown uploads for a project.
	//
	// GitLab API Docs:
	// https://docs.gitlab.com/ee/api/project_markdown_uploads.html#list-uploads
	ListProjectMarkdownUploads(pid interface{}, options ...RequestOptionFunc) ([]*ProjectMarkdownUpload, *Response, error)
	// DownloadProjectMarkdownUploadByID downloads a specific upload by ID.
	//
	// GitLab API Docs:
	// https://docs.gitlab.com/ee/api/project_markdown_uploads.html#download-an-uploaded-file-by-id
	DownloadProjectMarkdownUploadByID(pid interface{}, uploadID int, options ...RequestOptionFunc) ([]byte, *Response, error)
	// DownloadProjectMarkdownUploadBySecretAndFilename downloads a specific upload
	// by secret and filename.
	//
	// GitLab API Docs:
	// https://docs.gitlab.com/ee/api/project_markdown_uploads.html#download-an-uploaded-file-by-secret-and-filename
	DownloadProjectMarkdownUploadBySecretAndFilename(pid interface{}, secret string, filename string, options ...RequestOptionFunc) ([]byte, *Response, error)
	// DeleteProjectMarkdownUploadByID deletes an upload by ID.
	//
	// GitLab API Docs:
	// https://docs.gitlab.com/ee/api/project_markdown_uploads.html#delete-an-uploaded-file-by-id
	DeleteProjectMarkdownUploadByID(pid interface{}, uploadID int, options ...RequestOptionFunc) (*Response, error)
	// DeleteProjectMarkdownUploadBySecretAndFilename deletes an upload
	// by secret and filename.
	//
	// GitLab API Docs:
	// https://docs.gitlab.com/ee/api/project_markdown_uploads.html#delete-an-uploaded-file-by-secret-and-filename
	DeleteProjectMarkdownUploadBySecretAndFilename(pid interface{}, secret string, filename string, options ...RequestOptionFunc) (*Response, error)
}
