// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// ReleaseLinksService is an interface for [gitlab.Client.ReleaseLinks]
type ReleaseLinksService interface {
	// ListReleaseLinks gets assets as links from a Release.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/releases/links.html#list-links-of-a-release
	ListReleaseLinks(pid interface{}, tagName string, opt *ListReleaseLinksOptions, options ...RequestOptionFunc) ([]*ReleaseLink, *Response, error)
	// GetReleaseLink returns a link from release assets.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/releases/links.html#get-a-release-link
	GetReleaseLink(pid interface{}, tagName string, link int, options ...RequestOptionFunc) (*ReleaseLink, *Response, error)
	// CreateReleaseLink creates a link.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/releases/links.html#create-a-release-link
	CreateReleaseLink(pid interface{}, tagName string, opt *CreateReleaseLinkOptions, options ...RequestOptionFunc) (*ReleaseLink, *Response, error)
	// UpdateReleaseLink updates an asset link.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/releases/links.html#update-a-release-link
	UpdateReleaseLink(pid interface{}, tagName string, link int, opt *UpdateReleaseLinkOptions, options ...RequestOptionFunc) (*ReleaseLink, *Response, error)
	// DeleteReleaseLink deletes a link from release.
	//
	// GitLab API docs: https://docs.gitlab.com/ee/api/releases/links.html#delete-a-release-link
	DeleteReleaseLink(pid interface{}, tagName string, link int, options ...RequestOptionFunc) (*ReleaseLink, *Response, error)
}
