// Code generated by ifacemaker; DO NOT EDIT.

package gitlab

// ResourceWeightEventsService is an interface for [gitlab.Client.ResourceWeightEvents]
type ResourceWeightEventsService interface {
	// ListIssueWeightEvents retrieves resource weight events for the specified
	// project and issue.
	//
	// GitLab API docs:
	// https://docs.gitlab.com/ee/api/resource_weight_events.html#list-project-issue-weight-events
	ListIssueWeightEvents(pid interface{}, issue int, opt *ListWeightEventsOptions, options ...RequestOptionFunc) ([]*WeightEvent, *Response, error)
}
