// Code generated by MockGen. DO NOT EDIT.
// Source: dockerfiletemplatesservice_inf.go
//
// Generated by this command:
//
//	mockgen -package=mocks -source=dockerfiletemplatesservice_inf.go -destination=mocks/dockerfiletemplatesservice_inf.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gitlab "gitlab.com/gitlab-org/api/client-go"
	gomock "go.uber.org/mock/gomock"
)

// MockDockerfileTemplatesService is a mock of DockerfileTemplatesService interface.
type MockDockerfileTemplatesService struct {
	ctrl     *gomock.Controller
	recorder *MockDockerfileTemplatesServiceMockRecorder
	isgomock struct{}
}

// MockDockerfileTemplatesServiceMockRecorder is the mock recorder for MockDockerfileTemplatesService.
type MockDockerfileTemplatesServiceMockRecorder struct {
	mock *MockDockerfileTemplatesService
}

// NewMockDockerfileTemplatesService creates a new mock instance.
func NewMockDockerfileTemplatesService(ctrl *gomock.Controller) *MockDockerfileTemplatesService {
	mock := &MockDockerfileTemplatesService{ctrl: ctrl}
	mock.recorder = &MockDockerfileTemplatesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDockerfileTemplatesService) EXPECT() *MockDockerfileTemplatesServiceMockRecorder {
	return m.recorder
}

// GetTemplate mocks base method.
func (m *MockDockerfileTemplatesService) GetTemplate(key string, options ...gitlab.RequestOptionFunc) (*gitlab.DockerfileTemplate, *gitlab.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTemplate", varargs...)
	ret0, _ := ret[0].(*gitlab.DockerfileTemplate)
	ret1, _ := ret[1].(*gitlab.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockDockerfileTemplatesServiceMockRecorder) GetTemplate(key any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockDockerfileTemplatesService)(nil).GetTemplate), varargs...)
}

// ListTemplates mocks base method.
func (m *MockDockerfileTemplatesService) ListTemplates(opt *gitlab.ListDockerfileTemplatesOptions, options ...gitlab.RequestOptionFunc) ([]*gitlab.DockerfileTemplateListItem, *gitlab.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{opt}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTemplates", varargs...)
	ret0, _ := ret[0].([]*gitlab.DockerfileTemplateListItem)
	ret1, _ := ret[1].(*gitlab.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTemplates indicates an expected call of ListTemplates.
func (mr *MockDockerfileTemplatesServiceMockRecorder) ListTemplates(opt any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{opt}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplates", reflect.TypeOf((*MockDockerfileTemplatesService)(nil).ListTemplates), varargs...)
}
